import json
import os
import sys
import tempfile
import time
import types
import unittest
import importlib.util
import importlib.machinery
from unittest import mock

from flask import Flask
from flask import Blueprint


PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

def _install_dependency_stubs() -> None:
    if "cv2" not in sys.modules:
        cv2_stub = types.ModuleType("cv2")
        cv2_stub.__spec__ = importlib.machinery.ModuleSpec("cv2", loader=None)
        sys.modules["cv2"] = cv2_stub

    if "openai" not in sys.modules:
        openai_stub = types.ModuleType("openai")

        class _OpenAI:  # pragma: no cover - import stub only
            def __init__(self, *args, **kwargs):
                pass

        openai_stub.OpenAI = _OpenAI
        openai_stub.__spec__ = importlib.machinery.ModuleSpec("openai", loader=None)
        sys.modules["openai"] = openai_stub

    if "torch" not in sys.modules:
        torch_stub = types.ModuleType("torch")
        torch_stub.cuda = types.SimpleNamespace(is_available=lambda: False)
        torch_stub.__spec__ = importlib.machinery.ModuleSpec("torch", loader=None)
        sys.modules["torch"] = torch_stub


def tearDownModule():
    for module_name in ("cv2", "openai", "torch"):
        sys.modules.pop(module_name, None)


def _write_plugin(plugin_dir: str, plugin_id: str, class_name: str = "ExistingPlugin") -> None:
    os.makedirs(plugin_dir, exist_ok=True)
    with open(os.path.join(plugin_dir, "__init__.py"), "w", encoding="utf-8") as file:
        file.write(f"from .plugin import {class_name}\n")
    with open(os.path.join(plugin_dir, "plugin.py"), "w", encoding="utf-8") as file:
        file.write(
            "from src.plugins.base import PluginBase\n\n"
            f"class {class_name}(PluginBase):\n"
            f"    plugin_id = {plugin_id!r}\n"
            f"    display_name = {plugin_id!r}\n"
            "    plugin_version = '1.0.0'\n"
            "    plugin_author = 'Tests'\n"
            "    plugin_description = 'test plugin'\n"
            "    default_enabled = False\n"
            "    supported_steps = ('ocr',)\n"
            "    supported_modes = ('standard',)\n"
            "    def after_ocr(self, context, result):\n"
            "        return result\n"
        )


class FakePluginAgentController:
    def plan_turn(self, session, skill_markdown, agent_config):
        if not skill_markdown:
            raise AssertionError("skill markdown should be injected")
        if session.mode == "create" and session.pending_target is None and session.locked_target is None:
            return {
                "assistant_message": "我建议创建一个新插件。",
                "target_proposal": {
                    "plugin_id": "auto_plugin",
                    "display_name": "Auto Plugin",
                    "supported_steps": ["ocr"],
                    "supported_modes": ["standard"],
                },
            }
        return {
            "assistant_message": "已记录需求。",
        }

    def execute(self, session, skill_markdown, agent_config, tool_executor, emit_event):
        if not skill_markdown:
            raise AssertionError("skill markdown should be injected")
        emit_event("log", {"message": "开始执行"})
        if session.locked_target is None:
            raise RuntimeError("locked target missing")
        plugin_id = session.locked_target.plugin_id
        class_name = "".join(part.capitalize() for part in plugin_id.split("_")) or "GeneratedPlugin"
        tool_executor.write_file("__init__.py", f"from .plugin import {class_name}\n")
        tool_executor.write_file(
            "plugin.py",
            "from src.plugins.base import PluginBase\n\n"
            f"class {class_name}(PluginBase):\n"
            f"    plugin_id = {plugin_id!r}\n"
            f"    display_name = {session.locked_target.display_name!r}\n"
            "    plugin_version = '1.0.0'\n"
            "    plugin_author = 'Agent'\n"
            "    plugin_description = 'generated by tests'\n"
            "    default_enabled = False\n"
            "    supported_steps = ('ocr',)\n"
            "    supported_modes = ('standard',)\n"
            "    def after_ocr(self, context, result):\n"
            "        return result\n",
        )
        validation = tool_executor.validate_plugin()
        emit_event("validation", validation)
        return {
            "assistant_message": "插件已生成完成。",
            "refresh_plugins": True,
            "validation": validation,
        }


class SlowCancelAwareController:
    def plan_turn(self, session, skill_markdown, agent_config):
        return {"assistant_message": "已记录需求。"}

    def execute(self, session, skill_markdown, agent_config, tool_executor, emit_event):
        deadline = time.time() + 2.0
        while time.time() < deadline:
            if tool_executor.is_cancelled():
                raise RuntimeError("任务已取消")
            time.sleep(0.05)
        return {
            "assistant_message": "不应执行到这里",
            "refresh_plugins": False,
            "validation": {"success": True},
        }


class FakeStreamingTransport:
    def __init__(self, payloads, chunk_splits):
        self.payloads = list(payloads)
        self.chunk_splits = list(chunk_splits)

    def complete(self, request, resolved_invocation=None, before_request=None):
        if before_request is not None:
            before_request()
        payload = self.payloads.pop(0)
        chunks = self.chunk_splits.pop(0)
        callback = getattr(request.runtime_options, "on_stream_chunk", None)
        if callback:
            full_text = ""
            for size in chunks:
                segment = payload[len(full_text): len(full_text) + size]
                full_text += segment
                callback(segment, full_text)
            if len(full_text) < len(payload):
                segment = payload[len(full_text):]
                full_text += segment
                callback(segment, full_text)
        return payload


class PluginAgentRuntimeTests(unittest.TestCase):
    def setUp(self) -> None:
        _install_dependency_stubs()
        from src.core.plugin_agent.controller import PluginAgentController
        from src.core.plugin_agent.runtime import PluginAgentRuntime
        from src.core.plugin_agent.models import PluginAgentMessage
        from src.core.plugin_agent.tools import LockedPluginTarget, PluginAgentToolExecutor
        from src.shared.openai_options import create_openai_compatible_options

        self.PluginAgentController = PluginAgentController
        self.PluginAgentRuntime = PluginAgentRuntime
        self.PluginAgentMessage = PluginAgentMessage
        self.LockedPluginTarget = LockedPluginTarget
        self.PluginAgentToolExecutor = PluginAgentToolExecutor
        self.create_openai_compatible_options = create_openai_compatible_options

    def test_tool_executor_rejects_path_escape_outside_locked_plugin(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            target_dir = os.path.join(plugins_root, "safe_plugin")
            _write_plugin(target_dir, "safe_plugin", class_name="SafePlugin")

            target = self.LockedPluginTarget(
                mode="modify",
                plugin_id="safe_plugin",
                display_name="Safe Plugin",
                plugin_dir=target_dir,
            )
            executor = self.PluginAgentToolExecutor(target=target, skill_markdown="skill")

            with self.assertRaisesRegex(ValueError, "插件目录"):
                executor.read_file("../other_plugin/plugin.py")

            with self.assertRaisesRegex(ValueError, "插件目录"):
                executor.write_file("..\\outside.py", "print('bad')")

    def test_controller_prompts_require_json_only_output_without_outer_text(self) -> None:
        controller = self.PluginAgentController()
        planning_runtime = self.PluginAgentRuntime(
            plugins_root=os.path.join(tempfile.gettempdir(), "plugin-agent-tests"),
            controller=controller,
            finalize_refresh=lambda _target: None,
            skill_markdown="skill",
        )
        planning_session = planning_runtime.create_session("create")
        planning_prompt = controller._build_planning_system_prompt(planning_session)

        self.assertIn("你的回答必须且只能是一个合法 JSON 对象", planning_prompt)
        self.assertIn("JSON 的第一个非空字符必须是 `{`", planning_prompt)
        self.assertIn("JSON 外面禁止输出任何额外内容", planning_prompt)
        self.assertIn("不要输出“下面是 JSON”", planning_prompt)

        locked_target = self.LockedPluginTarget(
            mode="create",
            plugin_id="strict_json_plugin",
            display_name="Strict JSON Plugin",
            plugin_dir=os.path.join(tempfile.gettempdir(), "strict_json_plugin"),
        )
        planning_session.locked_target = locked_target
        execution_prompt = controller._build_execution_system_prompt(
            planning_session,
            recent_results=[],
            iteration=1,
        )

        self.assertIn("你的回答必须且只能是一个合法 JSON 对象", execution_prompt)
        self.assertIn("JSON 的第一个非空字符必须是 `{`", execution_prompt)
        self.assertIn("JSON 外面禁止输出任何额外内容", execution_prompt)
        self.assertIn("不要输出“下面是 JSON”", execution_prompt)

    def test_validate_plugin_runs_in_isolated_mode(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            target_dir = os.path.join(plugins_root, "validate_me")
            _write_plugin(target_dir, "validate_me", class_name="ValidateMePlugin")

            target = self.LockedPluginTarget(
                mode="modify",
                plugin_id="validate_me",
                display_name="Validate Me",
                plugin_dir=target_dir,
            )
            executor = self.PluginAgentToolExecutor(target=target, skill_markdown="skill")

            result = executor.validate_plugin()

            self.assertTrue(result["success"])
            self.assertEqual(result["plugin"]["id"], "validate_me")
            self.assertEqual(result["plugin"]["display_name"], "validate_me")

    def test_create_flow_requires_target_lock_before_execution(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            refresh_calls = []
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda target: refresh_calls.append(target.plugin_id),
                skill_markdown="skill",
            )

            session = runtime.create_session("create")
            runtime.send_user_message(session.session_id, "做一个OCR后清洗插件", {})
            self.assertEqual(runtime.get_session(session.session_id).run_state, "awaiting_target_lock")

            with self.assertRaisesRegex(ValueError, "锁定"):
                runtime.start_execution(session.session_id, {})

            runtime.lock_target(
                session.session_id,
                {
                    "plugin_id": "auto_plugin",
                    "display_name": "Auto Plugin",
                    "supported_steps": ["ocr"],
                    "supported_modes": ["standard"],
                },
            )
            runtime.start_execution(session.session_id, {})

            deadline = time.time() + 3.0
            while time.time() < deadline:
                updated = runtime.get_session(session.session_id)
                if updated and updated.run_state in {"completed", "failed"}:
                    break
                time.sleep(0.05)

            updated = runtime.get_session(session.session_id)
            self.assertIsNotNone(updated)
            self.assertEqual(updated.run_state, "completed")
            self.assertEqual(updated.locked_target.plugin_id, "auto_plugin")
            self.assertIn("auto_plugin", refresh_calls)
            self.assertTrue(os.path.exists(os.path.join(plugins_root, "auto_plugin", "plugin.py")))
            self.assertTrue(any(event.type == "log" for event in updated.events))
            self.assertTrue(any(event.type == "done" for event in updated.events))

    def test_delete_session_cancels_running_execution_without_leaking_active_session(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            plugin_dir = os.path.join(plugins_root, "existing_plugin")
            _write_plugin(plugin_dir, "existing_plugin", class_name="ExistingPlugin")

            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=SlowCancelAwareController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )
            session = runtime.create_session_with_display_name(
                "modify",
                plugin_id="existing_plugin",
                display_name="Existing Plugin",
            )
            session.messages.append(
                self.PluginAgentMessage(
                    id="user_1",
                    role="user",
                    content="修改这个插件",
                )
            )
            runtime.start_execution(session.session_id, {})

            deleted = runtime.delete_session(session.session_id)
            self.assertTrue(deleted)
            cancelled_session = runtime.get_session(session.session_id)
            self.assertIsNotNone(cancelled_session)
            self.assertEqual(cancelled_session.run_state, "cancelled")

            deadline = time.time() + 3.0
            while time.time() < deadline:
                thread = runtime._running_threads.get(session.session_id)
                if thread is None or not thread.is_alive():
                    break
                time.sleep(0.05)

            self.assertNotIn(session.session_id, runtime._running_threads)
            self.assertNotIn(session.session_id, runtime._cancel_flags)
            self.assertIsNone(runtime.get_session(session.session_id))

    def test_controller_streams_only_assistant_message_and_tool_result_includes_file_updates(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            plugin_dir = os.path.join(plugins_root, "stream_plugin")
            payloads = [
                json.dumps(
                    {
                        "assistant_message": "正在创建插件\n```python\nprint(\"ok\")\n```",
                        "action": {
                            "tool": "write_file",
                            "args": {
                                "path": "__init__.py",
                                "content": "from .plugin import StreamPlugin\n",
                            },
                        },
                    },
                    ensure_ascii=False,
                ),
                json.dumps(
                    {
                        "assistant_message": "继续写入主插件文件",
                        "action": {
                            "tool": "write_file",
                            "args": {
                                "path": "plugin.py",
                                "content": (
                                    "from src.plugins.base import PluginBase\n\n"
                                    "class StreamPlugin(PluginBase):\n"
                                    "    plugin_id = 'stream_plugin'\n"
                                    "    display_name = 'Stream Plugin'\n"
                                    "    plugin_version = '1.0.0'\n"
                                    "    plugin_author = 'Tests'\n"
                                    "    plugin_description = 'streamed plugin'\n"
                                    "    default_enabled = False\n"
                                    "    supported_steps = ('ocr',)\n"
                                    "    supported_modes = ('standard',)\n"
                                    "    def after_ocr(self, context, result):\n"
                                    "        return result\n"
                                ),
                            },
                        },
                    },
                    ensure_ascii=False,
                ),
                json.dumps(
                    {
                        "assistant_message": "开始校验插件",
                        "action": {
                            "tool": "validate_plugin",
                            "args": {},
                        },
                    },
                    ensure_ascii=False,
                ),
                json.dumps(
                    {
                        "assistant_message": "插件已经完成",
                        "action": {
                            "tool": "finish",
                            "args": {},
                        },
                    },
                    ensure_ascii=False,
                ),
            ]

            controller = self.PluginAgentController(
                transport=FakeStreamingTransport(
                    payloads=payloads,
                    chunk_splits=[
                        [24, 12, 8, 15],
                        [18, 9, 7, 11],
                        [10, 8, 6],
                        [12, 7, 5],
                    ],
                )
            )
            target = self.LockedPluginTarget(
                mode="create",
                plugin_id="stream_plugin",
                display_name="Stream Plugin",
                plugin_dir=plugin_dir,
            )
            executor = self.PluginAgentToolExecutor(target=target, skill_markdown="skill")
            session = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=controller,
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            ).create_session("create")
            session.locked_target = target
            session.run_state = "ready"
            session.messages.append(
                self.PluginAgentMessage(
                    id="user_1",
                    role="user",
                    content="做一个流式插件",
                )
            )
            events = []
            agent_config = {
                "provider": "custom",
                "api_key": "test-key",
                "model_name": "gpt-test",
                "custom_base_url": "https://example.com/v1",
                "openai_options": self.create_openai_compatible_options(
                    use_stream=True,
                    transport_retries=0,
                    business_retries=0,
                ),
            }

            result = controller.execute(
                session,
                "skill",
                agent_config,
                executor,
                lambda event_type, payload: events.append((event_type, payload)),
            )

            assistant_delta_events = [payload for event_type, payload in events if event_type == "assistant_delta"]
            self.assertGreaterEqual(len(assistant_delta_events), 1)
            self.assertTrue(any("print(\"ok\")" in payload["content"] for payload in assistant_delta_events))
            self.assertTrue(all('"tool"' not in payload["content"] for payload in assistant_delta_events))

            tool_results = [payload for event_type, payload in events if event_type == "tool_result"]
            self.assertGreaterEqual(len(tool_results), 2)
            self.assertTrue(any("__init__.py" in payload.get("changed_files", []) for payload in tool_results))
            self.assertTrue(any("plugin.py" in payload.get("changed_files", []) for payload in tool_results))
            self.assertTrue(any(payload.get("file_previews", {}).get("plugin.py") for payload in tool_results))

            validation_events = [payload for event_type, payload in events if event_type == "validation"]
            self.assertEqual(len(validation_events), 1)
            self.assertTrue(validation_events[0]["success"])
            self.assertEqual(result["assistant_message"], "插件已经完成")

    def test_controller_emits_multiple_assistant_deltas_for_short_fast_stream_output(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            plugin_dir = os.path.join(plugins_root, "stream_plugin")
            plugin_content = (
                "from src.plugins.base import PluginBase\n\n"
                "class StreamPlugin(PluginBase):\n"
                "    plugin_id = 'stream_plugin'\n"
                "    display_name = 'Stream Plugin'\n"
                "    plugin_version = '1.0.0'\n"
                "    plugin_author = 'Tests'\n"
                "    plugin_description = 'streamed plugin'\n"
                "    default_enabled = False\n"
                "    supported_steps = ('ocr',)\n"
                "    supported_modes = ('standard',)\n"
                "    def after_ocr(self, context, result):\n"
                "        return result\n"
            )
            payloads = [
                json.dumps(
                    {
                        "assistant_message": "开始写。",
                        "action": {
                            "tool": "write_file",
                            "args": {
                                "path": "__init__.py",
                                "content": "from .plugin import StreamPlugin\n",
                            },
                        },
                    },
                    ensure_ascii=False,
                ),
                json.dumps(
                    {
                        "assistant_message": "继续。",
                        "action": {
                            "tool": "write_file",
                            "args": {
                                "path": "plugin.py",
                                "content": plugin_content,
                            },
                        },
                    },
                    ensure_ascii=False,
                ),
                json.dumps(
                    {
                        "assistant_message": "校验。",
                        "action": {"tool": "validate_plugin", "args": {}},
                    },
                    ensure_ascii=False,
                ),
                json.dumps(
                    {
                        "assistant_message": "完成。",
                        "action": {"tool": "finish", "args": {}},
                    },
                    ensure_ascii=False,
                ),
            ]
            controller = self.PluginAgentController(
                transport=FakeStreamingTransport(
                    payloads=payloads,
                    chunk_splits=[
                        [1] * len(payloads[0]),
                        [1] * len(payloads[1]),
                        [1] * len(payloads[2]),
                        [1] * len(payloads[3]),
                    ],
                )
            )
            target = self.LockedPluginTarget(
                mode="create",
                plugin_id="stream_plugin",
                display_name="Stream Plugin",
                plugin_dir=plugin_dir,
            )
            executor = self.PluginAgentToolExecutor(target=target, skill_markdown="skill")
            session = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=controller,
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            ).create_session("create")
            session.locked_target = target
            session.run_state = "ready"
            session.messages.append(
                self.PluginAgentMessage(
                    id="user_1",
                    role="user",
                    content="做一个流式插件",
                )
            )
            events = []
            agent_config = {
                "provider": "custom",
                "api_key": "test-key",
                "model_name": "gpt-test",
                "custom_base_url": "https://example.com/v1",
                "openai_options": self.create_openai_compatible_options(
                    use_stream=True,
                    transport_retries=0,
                    business_retries=0,
                ),
            }

            controller.execute(
                session,
                "skill",
                agent_config,
                executor,
                lambda event_type, payload: events.append((event_type, payload)),
            )

            first_iteration_deltas = [
                payload for event_type, payload in events
                if event_type == "assistant_delta" and payload.get("stream_id") == "execution-1"
            ]
            self.assertGreaterEqual(len(first_iteration_deltas), 3)


class PluginAgentApiTests(unittest.TestCase):
    def setUp(self) -> None:
        _install_dependency_stubs()
        from src.core.plugin_agent.runtime import PluginAgentRuntime

        self.PluginAgentRuntime = PluginAgentRuntime
        system_dir = os.path.join(PROJECT_ROOT, "src", "app", "api", "system")
        package_name = "isolated_plugin_agent_system"
        package_module = types.ModuleType(package_name)
        package_module.__path__ = [system_dir]
        package_module.system_bp = Blueprint("isolated_system_api", __name__, url_prefix="/api")
        sys.modules[package_name] = package_module

        module_path = os.path.join(system_dir, "plugin_agent.py")
        spec = importlib.util.spec_from_file_location(f"{package_name}.plugin_agent", module_path)
        module = importlib.util.module_from_spec(spec)
        assert spec is not None and spec.loader is not None
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        self.plugin_agent_module = module

        self.app = Flask(__name__)
        self.app.register_blueprint(package_module.system_bp)
        self.client = self.app.test_client()

    def test_settings_endpoint_returns_examples(self) -> None:
        response = self.client.get("/api/plugins/agent/settings")

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertTrue(payload["success"])
        self.assertIn("prompt_examples", payload)
        self.assertGreaterEqual(len(payload["prompt_examples"]), 3)
        self.assertIsNone(payload["session"])

    def test_parse_agent_config_uses_updated_backend_defaults(self) -> None:
        parsed = self.plugin_agent_module._parse_agent_config({})

        self.assertEqual(parsed["openai_options"].execution.rpm_limit, 0)
        self.assertEqual(parsed["openai_options"].execution.transport_retries, 10)
        self.assertEqual(parsed["openai_options"].execution.business_retries, 10)

    def test_get_plugin_agent_runtime_uses_app_root_plugins_directory(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            self.plugin_agent_module._plugin_agent_runtime = None
            with mock.patch.object(self.plugin_agent_module, "get_app_root", return_value=temp_dir):
                runtime = self.plugin_agent_module.get_plugin_agent_runtime()

        self.assertEqual(runtime.plugins_root, os.path.join(temp_dir, "plugins"))

    def test_modify_session_requires_existing_plugin(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )

            with mock.patch.object(self.plugin_agent_module, "get_plugin_agent_runtime", return_value=runtime):
                response = self.client.post(
                    "/api/plugins/agent/sessions",
                    json={"mode": "modify", "plugin_id": "missing_plugin"},
                )

        self.assertEqual(response.status_code, 400)
        self.assertIn("插件不存在", response.get_json()["error"])

    def test_modify_session_locks_selected_plugin_immediately(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            _write_plugin(os.path.join(plugins_root, "existing_plugin"), "existing_plugin")
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )

            with mock.patch.object(self.plugin_agent_module, "get_plugin_agent_runtime", return_value=runtime):
                response = self.client.post(
                    "/api/plugins/agent/sessions",
                    json={"mode": "modify", "plugin_id": "existing_plugin"},
                )

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertTrue(payload["success"])
        self.assertEqual(payload["session"]["locked_target"]["plugin_id"], "existing_plugin")

    def test_create_session_start_is_blocked_before_lock_target(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )

            with mock.patch.object(self.plugin_agent_module, "get_plugin_agent_runtime", return_value=runtime):
                create_response = self.client.post("/api/plugins/agent/sessions", json={"mode": "create"})
                session_id = create_response.get_json()["session"]["session_id"]

                send_response = self.client.post(
                    f"/api/plugins/agent/sessions/{session_id}/messages",
                    json={"content": "请做一个OCR插件", "agent_config": {}},
                )
                self.assertEqual(send_response.status_code, 200)

                start_response = self.client.post(
                    f"/api/plugins/agent/sessions/{session_id}/start",
                    json={"agent_config": {}},
                )

        self.assertEqual(start_response.status_code, 409)
        self.assertIn("锁定", start_response.get_json()["error"])

    def test_event_stream_contains_assistant_event_after_plan_turn(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )

            with mock.patch.object(self.plugin_agent_module, "get_plugin_agent_runtime", return_value=runtime):
                create_response = self.client.post("/api/plugins/agent/sessions", json={"mode": "create"})
                session_id = create_response.get_json()["session"]["session_id"]

                self.client.post(
                    f"/api/plugins/agent/sessions/{session_id}/messages",
                    json={"content": "请做一个OCR插件", "agent_config": {}},
                )
                stream_response = self.client.get(f"/api/plugins/agent/sessions/{session_id}/events?after_id=0")

        self.assertEqual(stream_response.status_code, 200)
        body = b"".join(stream_response.response).decode("utf-8")
        self.assertIn("event: assistant", body)
        self.assertIn("event: state", body)


if __name__ == "__main__":
    unittest.main()
